##
# SCC025 - Trabalho 1
#
# @file *.c
# @version 0.1

ARQ_SAIDA=programaTrab

all:
	gcc *.c -o $(ARQ_SAIDA)

run:
	./$(ARQ_SAIDA)

debug:
	gcc *.c -o $(ARQ_SAIDA) -g

val:
	valgrind ./$(ARQ_SAIDA)

clear:
	rm $(ARQ_SAIDA)

# end
